from typing import Protocol
from uuid import UUID


class ContentRepository(Protocol):
    def get(self, content_id: UUID) -> object | None: ...
    def add(self, content: object) -> object: ...


class RunRepository(Protocol):
    def get(self, run_id: UUID) -> object | None: ...
    def get_by_key(self, run_key: str) -> object | None: ...
    def add(self, run: object) -> object: ...
