from enum import StrEnum


class ContentCategory(StrEnum):
    TREND_HISTORY = "TREND_HISTORY"
    AYT_HISTORY = "AYT_HISTORY"
    HISTORY_FACT = "HISTORY_FACT"
    CUSTOM = "CUSTOM"
    TODAY_IN_HISTORY = "TODAY_IN_HISTORY"


class ContentStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class TopicStatus(StrEnum):
    NEW = "NEW"
    EVALUATING = "EVALUATING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    USED = "USED"


class ScriptStatus(StrEnum):
    DRAFT = "DRAFT"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class SceneStatus(StrEnum):
    PLANNED = "PLANNED"
    READY = "READY"
    FAILED = "FAILED"


class AssetType(StrEnum):
    IMAGE = "IMAGE"
    VIDEO = "VIDEO"
    STOCK_IMAGE = "STOCK_IMAGE"
    STOCK_VIDEO = "STOCK_VIDEO"
    TTS = "TTS"
    MUSIC = "MUSIC"
    SFX = "SFX"
    THUMBNAIL = "THUMBNAIL"


class AssetStatus(StrEnum):
    PLANNED = "PLANNED"
    GENERATING = "GENERATING"
    READY = "READY"
    FAILED = "FAILED"


class RunType(StrEnum):
    SCHEDULED = "SCHEDULED"
    MANUAL = "MANUAL"
    CUSTOM = "CUSTOM"
    REGENERATE = "REGENERATE"
    RETRY = "RETRY"


class RunStatus(StrEnum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    RESEARCHING = "RESEARCHING"
    TOPIC_VALIDATION = "TOPIC_VALIDATION"
    SCRIPTING = "SCRIPTING"
    STORYBOARDING = "STORYBOARDING"
    ASSET_PLANNING = "ASSET_PLANNING"
    ASSET_GENERATION = "ASSET_GENERATION"
    TTS = "TTS"
    AUDIO_MIX = "AUDIO_MIX"
    RENDERING = "RENDERING"
    QC = "QC"
    READY_FOR_APPROVAL = "READY_FOR_APPROVAL"
    APPROVED = "APPROVED"
    PUBLISHING = "PUBLISHING"
    PUBLISHED = "PUBLISHED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_PROVIDER = "FAILED_PROVIDER"
    FAILED_QC = "FAILED_QC"
    FAILED_PERMANENT = "FAILED_PERMANENT"
    CANCELLED = "CANCELLED"


class Stage(StrEnum):
    RESEARCH = "RESEARCH"
    TOPIC_VALIDATION = "TOPIC_VALIDATION"
    SCRIPTING = "SCRIPTING"
    STORYBOARDING = "STORYBOARDING"
    ASSET_PLANNING = "ASSET_PLANNING"
    ASSET_GENERATION = "ASSET_GENERATION"
    TTS = "TTS"
    AUDIO_MIX = "AUDIO_MIX"
    RENDERING = "RENDERING"
    QC = "QC"
    APPROVAL = "APPROVAL"
    PUBLISHING = "PUBLISHING"


class StageStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    RETRY_WAIT = "RETRY_WAIT"
    SUCCESS = "SUCCESS"
    FAILED_PERMANENT = "FAILED_PERMANENT"
    CANCELLED = "CANCELLED"


class ApprovalStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    REGENERATE = "REGENERATE"
    EDIT_REQUESTED = "EDIT_REQUESTED"
    EXPIRED = "EXPIRED"


class PublicationPlatform(StrEnum):
    YOUTUBE = "YOUTUBE"
    TIKTOK = "TIKTOK"


class PublicationStatus(StrEnum):
    PENDING = "PENDING"
    QUEUED = "QUEUED"
    UPLOADING = "UPLOADING"
    PUBLISHED = "PUBLISHED"
    FAILED_RETRYABLE = "FAILED_RETRYABLE"
    FAILED_PERMANENT = "FAILED_PERMANENT"


class ProviderCategory(StrEnum):
    LLM = "LLM"
    TTS = "TTS"
    IMAGE = "IMAGE"
    VIDEO = "VIDEO"
    MEDIA = "MEDIA"
    MUSIC = "MUSIC"
    SFX = "SFX"
    PUBLISH = "PUBLISH"
    ANALYTICS = "ANALYTICS"
    STORAGE = "STORAGE"


class ProviderHealthStatus(StrEnum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    COOLDOWN = "COOLDOWN"
    OPEN = "OPEN"
    DISABLED = "DISABLED"


class EventSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"
